cozzee/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('landingpage.urls', namespace='landingpage')),
    path('',include('APPComment.urls', namespace='APPComment')),
    path('',include('menupage.urls', namespace='menupage')),
    path('feedback/',include('feedback.urls', namespace='feedback')),
    path('user/',include('login.urls', namespace='login')),
]

feedback/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'feedback'

urlpatterns = [
    path('', views.feedback, name="feedback"),
    path('tambah_saran/', views.kritik_saran, name="kritik"),
    path('tambah_kritik/', views.saran_kritik, name="saran"),
]

landingpage/urls.py
from django.urls import path
from . import views

app_name = 'landingpage'

urlpatterns = [
  path('',views.index, name='index'),
  path('toko/<int:id>/',views.toko, name='toko'),
  path('tambahToko/',views.tambahToko, name='tambahToko'),
  path('cariKedai/',views.cariKedai, name='cariKedai'),
  path('ajaxInputKedai/',views.ajaxInputKedai, name='ajaxInputKedai'),
]

login/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = "login"
urlpatterns = [
    path('', views.indexView, name="login"),
    path('login/', LoginView.as_view(), name = 'login_url'),
    path('register/',views.registerView, name='register_url'),
    path('dashboard/', views.dashboardView, name="dashboard_url"),
    path('logout/',LogoutView.as_view(next_page="login:login"), name="logout_url")
 ]   

feedback/models.py
from django.db import models

# Create your models here.
class Feedback(models.Model):
    nama = models.CharField(max_length=50)
    usia = models.IntegerField()
    kritik_dan_saran = models.TextField(max_length=500)

feedback/forms.py
from django import forms
from .models import Feedback

class feedbackForm(forms.ModelForm):
    nama = forms.CharField(label = 'Nama', required=True)
    usia = forms.IntegerField(label = 'Usia', required=True)
    kritik_dan_saran = forms.CharField(label = 'Kritik dan Saran', widget=forms.Textarea, required=True)
    class Meta:
        model = Feedback
        fields = ('nama', 'usia', 'kritik_dan_saran')
        widgets = {'kritik_dan_saran': forms.Textarea()}

feedback/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from .forms import feedbackForm
from django.shortcuts import redirect
from .models import Feedback
from . import forms

# Create your views here.
def feedback(request):
    if request.method == 'POST':
        form = feedbackForm(request.POST)
        if form.is_valid():
            form.save()
            nama = form.cleaned_data['nama']
            usia = form.cleaned_data['usia']
            kritik_dan_saran = form.cleaned_data['kritik_dan_saran']
            return redirect('/feedback')
    else:
        form = feedbackForm()
    return render(request, 'feedback.html', {'form':form})

def kritik_saran(request):
    feedback = Feedback(
        nama = request.POST['nama'],
        usia = request.POST['usia'],
        kritik_dan_saran = request.POST['feedback']
    )

    feedback.save()
    return JsonResponse({"Status": "OK"})

def saran_kritik(request):
    feedbacks = Feedback.objects.filter(kritik_dan_saran__startswith=request.GET['nama'])
    if not feedbacks:
        return JsonResponse({'saran' : ''})
    response = {'saran' : feedbacks[0].kritik_dan_saran}
    return JsonResponse(response, safe=False)

feedback/templates/feedback.html
<html>
	{% load static %}
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href= "{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" href= "{% static 'css/bootstrap.min.css'%}">
	<link rel="stylesheet" href= "{% static 'js/bootstrap.js' %}">
	<link rel="stylesheet" href= "{% static 'js/bootstrap.min.js' %}">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<head>
	<title>Kritik dan Saran</title>
</head>
<style>
    textarea {
        width : 100%;
        background: #EFEDED;
        border: 1px solid #000000;
        box-sizing: border-box;
        box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
    }
    body {
        background-color:#EFE9DB;
        font-family: Quattrocento;
        margin-top: 2vw;
    }
    h1 {
        position: absolute;
        top: 3vw;

        font-family: Quattrocento;
        font-style: normal;
        font-weight: normal;
        font-size: 5vw;
        color: #354449;
    }
    .line {
        position: absolute;
        width: 80vw;
        height: 3px;
        top: 9vw;
        background: #D09780;
    }
    .form{
        margin-top: 10vw;
    }
    button, input {
        width:100%;
        background: #EFEDED;
        border: 1px solid #000000;
        box-sizing: border-box;
    }
    .txt{
        /* padding-right: 5%; */
        text-align: right;
    }
    .save{
        border: 1px solid #000000;
        width: 10vw;
        text-align: center;
        font-size: 2vw;
        box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
    }
    p {
        font-family: Quattrocento;
        font-style: normal;
        font-weight: normal;
        font-size: 25px;
        color: #354449;
    }
}    
</style>
<body>
    <div style="padding-left:5%;padding-right:5%;">
    <div class="container" >
        <div class="row">
            <h1>Kritik dan Saran</h1>
            <div class="line"></div>
            <div class="col-12 form">
                {% block content %}
                <form method="POST" class="post-form">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <p class= "temp"></p>
                <div class="txt">
                    <button type="submit" class="save btn btn-default kirim">Kirim</button>
                    <a class="save btn btn-default" href="{% url 'landingpage:index' %}">Kembali</a>
                </div>
                </form>
                {% endblock %}
            </div>
        </div>
    </div>
</div>
</body>
<script>
$(document).ready(function(){
    $('.save').hover(
        function(){
            $(this).css({ "background-color" : "rgba(206, 197, 174, 1)" });
        }, function(){
            $(this).css({ "background-color" : "rgba(239, 233, 219, 1)" });
    });
    $('.kirim').on('click', function(e) {
        e.preventDefault()
        $.post({
            url: `/feedback/tambah_saran/`,
            data: {
                'nama' : $("#id_nama").val(),
                'usia' : $("#id_usia").val(),
                'feedback' : $("#id_kritik_dan_saran").val(),
                'csrfmiddlewaretoken': $("[name=csrfmiddlewaretoken]").val()
            },
            dataType: 'json',
            success: function(response) {
                alert(`Terimakasih ${$("#id_nama").val()} atas Kritik dan Sarannya!`);
                $('.loader').hide();
                $("#id_nama").val("");
                $("#id_usia").val("")
                $("#id_kritik_dan_saran").val("")
            },
        });
        $.get({
                url: `/feedback/tambah_kritik/`,
                data: {
                    'nama' : $("#id_nama").val(),
                    'usia' : $("#id_usia").val(),
                    'feedback' : $("#id_kritik_dan_saran").val(),
                    'csrfmiddlewaretoken': $("[name=csrfmiddlewaretoken]").val()
                },
                dataType: 'json',
                success: function(response){
                    console.log(response)
                }
        })
    });
    $('#id_kritik_dan_saran').on('keyup', function(e) {
        // if (document.querySelector('#id_kritik_dan_saran').previousElementSibling.innerHTML != "Kritik dan Saran:"){
        //     $("#id_kritik_dan_saran").prev().remove()
        // }
        $.get({
                url: `/feedback/tambah_kritik/`,
                data: {
                    'nama' : $("#id_kritik_dan_saran").val().toLowerCase(),
                    // 'usia' : $("#id_usia").val(),
                    // 'feedback' : $("#id_kritik_dan_saran").val(),
                    // 'csrfmiddlewaretoken': $("[name=csrfmiddlewaretoken]").val()
                },
                dataType: 'json',
                success: function(response){
                    $(".temp").html(`Saran sebelumnya: ${response.saran}`)
                }
        })
    });
    
});
</script>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</html>