APPComment/urls.py
from django.contrib import admin
from django.urls import path
from .views import inputKomen, deleteKomen, index, ajaxInputKomen, ajaxCekNilai

app_name = 'APPComment'

urlpatterns = [
    path('adminSite/', admin.site.urls),
    path('indexComment/<int:id>/', index, name="indexComment"),
    path('input/<int:id>/', inputKomen, name="inputKomen"),
    path('ajaxInput/<int:id>/', ajaxInputKomen, name="ajaxInputKomen"),
    path('ajaxCekNilai/<int:id>/', ajaxCekNilai, name="ajaxCekNilai"),
    path('delete/', deleteKomen),
]

cozzee/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('landingpage.urls', namespace='landingpage')),
    path('',include('APPComment.urls', namespace='APPComment')),
    path('',include('menupage.urls', namespace='menupage')),
    path('feedback/',include('feedback.urls', namespace='feedback')),
    path('user/',include('login.urls', namespace='login')),
]

landingpage/urls.py
from django.urls import path
from . import views

app_name = 'landingpage'

urlpatterns = [
  path('',views.index, name='index'),
  path('toko/<int:id>/',views.toko, name='toko'),
  path('tambahToko/',views.tambahToko, name='tambahToko'),
  path('cariKedai/',views.cariKedai, name='cariKedai'),
  path('ajaxInputKedai/',views.ajaxInputKedai, name='ajaxInputKedai'),
]

login/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = "login"
urlpatterns = [
    path('', views.indexView, name="login"),
    path('login/', LoginView.as_view(), name = 'login_url'),
    path('register/',views.registerView, name='register_url'),
    path('dashboard/', views.dashboardView, name="dashboard_url"),
    path('logout/',LogoutView.as_view(next_page="login:login"), name="logout_url")
 ]   

menupage/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path
from menupage import views
from menupage.views import TambahMenu, TampilanMenu

app_name = 'menupage'

urlpatterns = [
    path('tambah-menu/<int:id>/', views.TambahMenu, name="tambah_menu"),
    path('tambah-menu-ajax/<int:id>/', views.TambahMenuAjax, name="tambah_menu_ajax"),
    path('menu-page/<int:id>/', views.TampilanMenu, name='menu_page'),
    path('menu/<int:id>/', views.cari_menu, name='menu'),
    # path('hapusmenu-page/', views.HapusMenu)
]

landingpage/models.py
from django.db import models

class TambahToko(models.Model):
    nama = models.CharField(max_length = 30)
    alamat = models.CharField(max_length = 100)
    jam_operasional = models.CharField(max_length = 50)
    nomor_telepon = models.CharField(max_length = 15)
    harga_per_orang = models.CharField(max_length = 20)
    fasilitas = models.TextField(max_length = 200)
    foto_url = models.URLField()

    def __str__(self):
        return self.nama

landingpage/forms.py
from django.forms import ModelForm
from .models import TambahToko

class TambahTokoForm(ModelForm):
    class Meta:
      model = TambahToko
      fields = '__all__'

landingpage/views.py
from django.shortcuts import render, redirect
from APPComment.models import simpanKomen
from APPComment.forms import formKomen
from django.http import JsonResponse
from .models import TambahToko
from .forms import TambahTokoForm

# Create your views here.

def index(request):
    context = {
        'kedai' : TambahToko.objects.all()
    }
    return render(request,'index.html', context)  

def toko(request, id, optional = None):
    kedai = TambahToko.objects.get(id = id)
    komen = simpanKomen.objects.filter(id_toko = id)

    if optional == None:
        countRasa = 0
        countSuasana = 0
        countPelayanan = 0
        for x in komen:
            countRasa += x.fieldRatingR
            countSuasana += x.fieldRatingS
            countPelayanan += x.fieldRatingP
        banyakIsi = simpanKomen.objects.filter(id_toko=id).count()
        if banyakIsi != 0:
            rataRataTotal = (countRasa+ countSuasana+ countPelayanan)/3
            countRasa = round(countRasa/banyakIsi, 1)
            countSuasana = round(countSuasana/banyakIsi, 1)
            countPelayanan = round(countPelayanan/banyakIsi, 1)
            rataRataTotal = round(rataRataTotal/banyakIsi, 1)
            formulir = formKomen()
            optional = {
                'generated_html' : formulir,
                'countR' : countRasa,
                'countS' : countSuasana,
                'countP' : countPelayanan,
                'rataTotal' : rataRataTotal
            }
        else:
            formulir = formKomen()
            optional = {
                'generated_html' : formulir,
                'countR' : 0.0,
                'countS' : 0.0,
                'countP' : 0.0,
                'rataTotal' : 0.0
            }

    return render(request,'toko.html', {'kedai' :kedai, 'komen' : komen, 'nilai': optional})


def tambahToko(request):
    form = TambahTokoForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect('/')

    return render(request, 'tambahToko.html', {
    'form' : form
  })

def cariKedai(request):
    tokos = TambahToko.objects.filter(nama__startswith=request.GET['data'])
    response = []
    for toko in tokos:
        tmpvar = {'nama' : toko.nama, 'foto' : toko.foto_url, 'id' : toko.id}
        response.append(tmpvar)
    return JsonResponse(response, safe=False)

def ajaxInputKedai(request):
    form = TambahTokoForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            baru = form.save()

    a = request.POST['nama']
    b = request.POST['alamat']
    c = request.POST['jam_operasional']
    d = request.POST['nomor_telepon']
    e = request.POST['harga_per_orang']
    f = request.POST['fasilitas']
    g = request.POST['foto_url']
    allToko = TambahToko.objects.all()
    data = {
        'nama' : a,
        'alamat' : b,
        'jam_operasional' : c,
        'nomor_telepon' : d,
        'harga_per_orang' : e,
        'fasilitas' : f,
        'foto_url' : g,
        'id' : baru.id
    }

    return JsonResponse(data)

landingpage/templates/index.html
{% extends "base.html" %} {% block content %}
{% load static %}
<input type='text' id="search" placeholder="   Cari kedai kopi kesukaanmu....">
<div class="row my-5 tabelToko">
    {%for kedai in kedai %}
  <div class="col-sm d-flex justify-content-center py-2">
    <div class="card" style="width: 18rem;">
      <a href="{% url 'landingpage:toko' id=kedai.id %}"
        ><img
          src="{{ kedai.foto_url }}"
          class="card-img-top"
          alt="Telegram Coffee"
          style="height: 200px;"
      /></a>
      <div class="card-body">
        <p class="card-text">
          {{kedai.nama}}
        </p>
      </div>
    </div>
    {% endfor %}
  </div>
<div>

{% endblock %}

landingpage/templates/tambahToko.html
{% load static %}
<head>
<html>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'js/bootstrap.js' %}">
    <link rel="stylesheet" href="{% static 'js/bootstrap.min.js' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <title>Tambah Menu Page</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>
    <div style="padding-left:5%;padding-right:5%;">
    <div class="container" >
    <h1>Tambah Kedai</h1>
    <div class="row">
        <div class="line"></div>
        <div class="col-12 form">
            {% block content %}
            <form class="formBuatToko" action="" method="POST">
            <table>
                {% csrf_token %}
                {{ form.as_table }}
                {% endblock %}
            </table>
            <div class="tolong">
                <input type="submit" value="Kirim" name="tombol" class="save btn btn-default buatToko">
                <!-- <a href="{% url 'landingpage:index' %}"><button type="submit" class="save btn btn-default buatToko">Kirim</button></a> -->
                <a href="{% url 'landingpage:index' %}"><button type = "button" class="save btn btn-default">Kembali</button></a>
            </div>
            </form>
        </div>
    </div>
    </div>
    </div>
    <script src="{% static 'script.js' %}"></script>
</body>

landingpage/templates/toko.html
{% extends "base.html" %} {% block content %}
{% load static %}

<div class="row my-4">
  <div class="col-md-6 d-flex justify-content-center align-items-center">
    <img
      src="{{ kedai.foto_url }}"
      class="card-img-top"
      alt="Telegram Coffee"
    />
  </div>
  <div class="col-md-6">
    <div class="row">
      <div class="col-sm" style="border-bottom: #D09780 2px solid; font-size: 2rem;">
        {{ kedai.nama }}
      </div>
    </div>
    {% if nilai == None %}
    <div class="row d-flex justify-content-around">
      <div class="col-xs-3">
        <div class="card">
          <h1
            class="badge badge-custom"
            style="border-bottom-right-radius: 0; border-bottom-left-radius: 0; font-size: 100%;"
          >
            Rasa
          </h1>
          <div class="card-body py-0 mt-n2">
            <p class="card-text text-center" style="font-size: 200%;">
              0.0
            </p>
          </div>
        </div>
      </div>
      <div class="col-xs-3">
            <div class="card">
                    <h1
                      class="badge badge-custom"
                      style="border-bottom-right-radius: 0; border-bottom-left-radius: 0; font-size: 100%;"
                    >
                      Suasana
                    </h1>
                    <div class="card-body py-0 mt-n2">
                      <p class="card-text text-center" style="font-size: 200%;">
                        0.0
                      </p>
                    </div>
                  </div>
      </div>
      <div class="col-xs-3">
            <div class="card">
                    <h1
                      class="badge badge-custom"
                      style="border-bottom-right-radius: 0; border-bottom-left-radius: 0; font-size: 100%;"
                    >
                      Pelayanan
                    </h1>
                    <div class="card-body py-0 mt-n2">
                      <p class="card-text text-center" style="font-size: 200%;">
                        0.0
                      </p>
                    </div>
                  </div>
      </div>
      <div class="col-xs-3">
            <div class="card">
                    <h1
                      class="badge badge-custom"
                      style="border-bottom-right-radius: 0; border-bottom-left-radius: 0; font-size: 100%;"
                    >
                      Total
                    </h1>
                    <div class="card-body py-0 mt-n2">
                      <p class="card-text text-center" style="font-size: 200%;">
                        0.0
                      </p>
                    </div>
                  </div>
      </div>
    </div>
    {% endif %}
    {% if nilai != none %}
    <div class="row d-flex justify-content-around">
        <div class="col-xs-3">
          <div class="card">
            <h1
              class="badge badge-custom"
              style="border-bottom-right-radius: 0; border-bottom-left-radius: 0; font-size: 100%;"
            >
              Rasa
            </h1>
            <div class="card-body py-0 mt-n2">
              <p class="card-text text-center countr" style="font-size: 200%;">
                {{nilai.countR}}
              </p>
            </div>
          </div>
        </div>
        <div class="col-xs-3">
              <div class="card">
                      <h1
                        class="badge badge-custom"
                        style="border-bottom-right-radius: 0; border-bottom-left-radius: 0; font-size: 100%;"
                      >
                        Suasana
                      </h1>
                      <div class="card-body py-0 mt-n2">
                        <p class="card-text text-center counts" style="font-size: 200%;">
                {{nilai.countS}}
                          
                        </p>
                      </div>
                    </div>
        </div>
        <div class="col-xs-3">
              <div class="card">
                      <h1
                        class="badge badge-custom"
                        style="border-bottom-right-radius: 0; border-bottom-left-radius: 0; font-size: 100%;"
                      >
                        Pelayanan
                      </h1>
                      <div class="card-body py-0 mt-n2">
                        <p class="card-text text-center countp" style="font-size: 200%;">
                {{nilai.countP}}
                          
                        </p>
                      </div>
                    </div>
        </div>
        <div class="col-xs-3">
              <div class="card">
                      <h1
                        class="badge badge-custom "
                        style="border-bottom-right-radius: 0; border-bottom-left-radius: 0; font-size: 100%;"
                      >
                        Total
                      </h1>
                      <div class="card-body py-0 mt-n2">
                        <p class="card-text text-center totalNilai" style="font-size: 200%;">
                {{nilai.rataTotal}}
                        </p>
                      </div>
                    </div>
        </div>
      </div>
    {% endif %}
    <div class="row">
        <div class="col-xs-1 px-1">
            <i class="fas fa-map-marker-alt"></i>
        </div>
        <div class="col-xs-11">
            <p>&nbsp; {{ kedai.alamat }}</p>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-1 px-1">
            <i class="far fa-clock"></i>
        </div>
        <div class="col-xs-11">
            <p>{{ kedai.jam_operasional }}</p>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-1 px-1">
            <i class="fas fa-phone"></i>
        </div>
        <div class="col-xs-11">
            <p>{{ kedai.nomor_telepon }}</p>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-1 px-1">
            <i class="fas fa-coins"></i>
        </div>
        <div class="col-xs-11">
            <p>{{ kedai.harga_per_orang }}</p>
        </div>        
    </div>
    <div class="row pos px-1">
        {{ kedai.fasilitas }}
    </div>
    <div class="row">
        <div class="col-sm cui">
            <div style = "margin-top: 3vw;"></div>
            <!-- <button type="button" class="save btn btn-default pos" data-toggle="modal" data-target="#exampleModal">Tulis Komentar</button> -->
            <!-- <a href="{% url 'APPComment:indexComment' kedai.id %}"><button class="save btn btn-default pos">Tulis Komentar</button> -->
            {% if user.is_anonymous %}
            <a href="{% url 'menupage:menu_page' kedai.id %}"><button class="save btn btn-default pos">Lihat Menu</button></a>
          {% else %}
          <button type="button" class="save btn btn-default pos" data-toggle="modal" data-target="#exampleModal">Tulis Komentar</button>
          <a href="{% url 'menupage:menu_page' kedai.id %}"><button class="save btn btn-default pos">Lihat Menu</button></a>
          {% endif %}
        </div>
    </div>
  </div>
</div>

<div class="body">
    <div class='container-fluid row komens' id='bgform'>
        {% for x in komen %}
        <div class="col-md-2">
            <img src="{% static 'images/fotoKomen.png' %}" alt="" class="foto">
        </div>
        <div class="glyphicon glyphicon-triangle-left"></div>
        <div class='col-md-9' id='kotakagenda'>
            <h3 id="namakegiatan">{{x.fieldJudulKomen}}</h3>
            <hr>
            <h5 class="isiK">{{x.fieldIsiKomen}}</h5>
            <hr>
            <ul class="list-inline">
                <li class="list-inline-item"><h5 class="rating">Rating Rasa            :{{x.fieldRatingR}}</h5></li>
                <li class="list-inline-item"><h5 class="rating">Rating Rasa            :{{x.fieldRatingS}}</h5></li>
                <li class="list-inline-item"><h5 class="rating">Rating Rasa            :{{x.fieldRatingP}}</h5></li>
            </ul>
        </div>
    {% endfor %}   
    </div>
    <div class="container-fluid tombol">
        <!-- <a href="/delete/"><button class="btn btn-danger" type="submit">Delete</button></a> -->
    </div>
    
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Tulis Komentar</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="POST" class="post-form submitForm">
          {% csrf_token %}
          <table>
            <div class="row">
              {{nilai.generated_html.as_table}}
            </div>
          </table>
          <div class="tolong">
            <input type="submit" value="Tambah" name="tombol" class="btn btn-secondary submitTombol" data-dismiss="modal">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Kembali</button>
          </div>
        </form>
      </div>
      <!-- <div class="modal-footer">
        <button type="button" class="btn btn-primary">Submit</button>
      </div> -->
    </div>
  </div>
</div>

{% endblock %}